### ISSUE TITLE
Not able to add groceries

### ISSUE THREAD

**Issue by mabakerm** [Retrospected/app.picnic#42] opened 2024-10-12 09:14 UTC
Hi, been using your app for a couple of years. I have recepies for my weekly, bi-weekly and monthly groceries. Since a few months the app is not able to order the products. I have reinstalled the application, authentication tests are succesfull, flow is executing, but no products showing up in my basket. What can I do?

Using early homey 2019 pro.

**Comment by Retrospected** [comment] 2024-10-12 09:17
Yes I'm afraid the picnic api has changed, something i have to debug and fix. Duplicate of [#41](https://github.com/Retrospected/app.picnic/issues/41). Will try to have a look soon!

**Comment by Retrospected** [comment] 2024-10-12 22:57
@mabakerm  it seems like i fixed it, could you test this out for me? https://homey.app/a/app.picnic/test/

**Closed** 2024-10-14 07:02 UTC

**Comment by mabakerm** [comment] 2024-10-14 17:25
Seems to work!! Thanks

Op ma 14 okt 2024 om 09:03 schreef Retrospected ***@***.***>
